name: Automatically create PR
on:
  push:
    branches:
      - feature/*

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GA_TOKEN }}
          commit-message: Create PR with changes
          base: master
          branch: ${{ github.ref }}
          title: \[${{ github.ref }}\] Pull Request
          body: jira-ticket