name: pg-application-container-cd
on: workflow_dispatch

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

  # 위 과정에서 푸시한 이미지를 ec2에서 풀받아서 실행시키는 과정
  run-docker-image-on-ec2:
    # build-docker-image (위)과정이 완료되어야 실행됩니다.
    needs: build-docker-image
    runs-on: ip-172-31-46-194

    steps:
      # 1. 최신 이미지를 풀받습니다
      - name: docker pull
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cicd-study

      # 2. 기존의 컨테이너를 중지시킵니다
      - name: docker stop container
        run: sudo docker-compose down app

      # 3. 최신 이미지를 컨테이너화하여 실행시킵니다
      - name: docker run new container
        run: sudo docker-compose up app -d

      # 4. 미사용 이미지를 정리합니다
      - name: delete old docker image
        run: sudo docker system prune -f