name: pg-application-ci
on: workflow_dispatch
#  push:
#    branches:
#      - master

env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 1. Set up Java 21 on Runner of Github Actions
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 2. Spring Boot 애플리케이션 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build

      # 3. Upload jar to workspace
      - name: Create Deployment Bundle
        run: |
          mkdir -p deployment/target
          cp -r build/libs/* deployment/target/
          zip -r deployment-$BUILD_NUMBER.zip deployment

      - name: Publish Deployment Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-artifact
          path: ${{github.workspace}}/deployment-${{ github.run_number }}.zip

  deploy:
    runs-on: ubuntu-latest
