name: on-premise-cicd
on:
  workflow_dispatch:
    inputs:  # v1.0.0 v1.0.1 v1.1.0 -> v-1-0-0
      tags:
        description: 'Set Tags Name'
        required: true
        default: master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.set-version.outputs.VERSION_NAME }}
    steps:
      - id: set-version
        name: Convert Release Name
        run: |
          echo "${{ github.event.inputs.tags }}"
          echo "VERSION_NAME=$(echo "${{ github.event.inputs.tags }}" | sed "s/\./\-/g")" >> $GIHUB_OUTPUT

      - name: Check Version Name # v1-0-0
        run: |
          echo "${{ github.set-version.outputs.VERSION_NAME }}"

      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.inputs.tags }}'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradlew
        run: ./gradlew clean bootJar

      - name: Add version -> cicd-study-vX-X-X.jar
        run: |
          mv build/libs/cicd-study-0.0.1-SNAPSHOT.jar build/libs/cicd-study-${{ github.set-version.outputs.VERSION_NAME }}.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicd-study-application
          path: build/libs/cicd-study-${{ github.set-version.outputs.VERSION_NAME }}.jar


#  deploy:
#    runs-on: ubuntu-latest
#    needs:
#      - build